### ISSUE TITLE
zh_cn should be zh_Hans_CN.csv

### ISSUE THREAD

**Issue by weilunallen** [Magento2Translations/language_zh_hans_cn#1]
after the composer install I couldn't find zh_cn install in the directory, instead I copy the zh_cn.csv file over to `app/design/frontend/[Namespace]/[ThemeName]/i18n/ ` and rename zh_cn.csv to  zh_Hans_CN.csv, and it works.  some Chinese translation is not very accurate, should be fix.

**Comment by MrGekko** [comment]
Thank you for your comments.
I changed the git repo and uploaded the changes to all the files.
For the actual translations i would like to point you to the [magento Crowdin repo](https://crowdin.com/project/magento-2/zh-CN) The translations from there are the resource for these git repo's.

But adding stuff to the crowdin project does not seem to result in a quickly updated pack as the crowdin project zip is not getting all the changes made before the translations are checked and approved.. I have no control over this process.

**Comment by MrGekko** [comment]
I tested it and it seems to work perfectly! What does the _hans say in language terms??
