### ISSUE TITLE
why composer ask for username and password

### ISSUE THREAD

**Issue by shyandsy** [Magento2Translations/language_zh_hans_cn#4]
why composer ask for username and password
![image](https://cloud.githubusercontent.com/assets/5271457/18502633/ccc9c42a-7a1d-11e6-94b3-8688ebb3b0ee.png)

**Comment by MrGekko** [comment]
Maybe you are using the Magento packages and they need a password? I d not think packagist requires a password. If you continue having this issue and know that it has to do with this repo please reopen the issue.
