### ISSUE TITLE
Wrong First Name Translation in Catalog

### ISSUE THREAD

**Issue by kevljones** [Magento2Translations/language_zh_hans_cn#5]
Hi.

Thanks for this great translation. We're using it on a Chinese site we have built but a Chinese speaking colleague of mine has pointed out that on the Create an Account page of Magento the same translation is used for first name / last name 

Looking through the csv its correctly translated for the backend admin area but not for the frontend catalog.

Is there a way to update this translation?

Also on the create account page she suggests that 订阅资讯 would be a better translation for 'Sign up for Newsletter'

I'm not sure how to amend these translations myself so thought it best to raise an issue.

Thanks

Kev

**Comment by MrGekko** [comment]
Hi you could edit the appropriate strings on crowdin:
https://crowdin.com/project/magento-2/zh-CN
It will be persisted to this package within 24 hours.

**Comment by kevljones** [comment]
Thanks for the quick response.

I will do that now and add any additional ones that may come to light during testing.

Kev
